import type { SelectionInput } from "./SelectionContext";

export interface SampleCase extends SelectionInput {
  caseTitle: string;
  notes: string;
  // extra display-only fields (not in selection schema, shown in UI/datasheet header later)
  clientName: string;
  areaUnit: string;
  lineNumber: string;
  lineClass: string;
  operatingPressure: string;
  operatingTemp: string;
  flowCondition: string;
}

export const SAMPLE_CASES: SampleCase[] = [
  {
    caseTitle: "Produced gas isolation valve",
    projectName: "North Sea Compression Upgrade",
    clientName: "NorthOil A/S",
    areaUnit: "Unit 200 — HP Compression",
    lineNumber: '8"-PG-201-A1A',
    tagNumber: "XV-2014",
    pipeSize: '8"',
    pressureClass: "600#",
    lineClass: "A1A — CS, Class 600",
    installationLocation: "Offshore - Topside",
    valveFunction: "Isolation (On/Off)",
    serviceType: "General Hydrocarbon",
    fluidType: "Gas / Vapor",
    designTemp: "95",
    designPressure: "98",
    operatingPressure: "82",
    operatingTemp: "68",
    flowCondition: "Continuous, dry gas",
    additionalRequirements: [
      "ESD / Emergency Shutdown",
      "Hazardous Area (ATEX / IECEx)",
      "Low Emission (Fugitive Emissions)",
    ],
    notes: "Topside HP produced gas isolation downstream of inlet separator. Fire-safe and ESD ready.",
  },
  {
    caseTitle: "Crude oil export pipeline valve",
    projectName: "Bonga Crude Export Tie-In",
    clientName: "ShellNG Upstream",
    areaUnit: "Unit 400 — Export Metering",
    lineNumber: '24"-CO-401-B2A',
    tagNumber: "MOV-4002",
    pipeSize: '24"',
    pressureClass: "600#",
    lineClass: "B2A — CS, Class 600 piggable",
    installationLocation: "Onshore - Open Air",
    valveFunction: "Isolation (On/Off)",
    serviceType: "General Hydrocarbon",
    fluidType: "Liquid - Clean",
    designTemp: "65",
    designPressure: "85",
    operatingPressure: "70",
    operatingTemp: "45",
    flowCondition: "Continuous, piggable line",
    additionalRequirements: [
      "Piggable Line (Full Bore Required)",
      "Bidirectional Sealing",
    ],
    notes: "Crude export trunk line block valve. Full-bore trunnion ball, double block & bleed capable.",
  },
  {
    caseTitle: "Condensate drain valve",
    projectName: "Karachaganak Phase 3 Debottlenecking",
    clientName: "KPO BV",
    areaUnit: "Unit 110 — Inlet Separation",
    lineNumber: '2"-CD-112-A1A',
    tagNumber: "HV-1124",
    pipeSize: '2"',
    pressureClass: "300#",
    lineClass: "A1A — CS, Class 300",
    installationLocation: "Onshore - Sheltered / Building",
    valveFunction: "Drain",
    serviceType: "General Hydrocarbon",
    fluidType: "Liquid - Clean",
    designTemp: "60",
    designPressure: "32",
    operatingPressure: "18",
    operatingTemp: "40",
    flowCondition: "Intermittent",
    additionalRequirements: ["Hazardous Area (ATEX / IECEx)"],
    notes: "Manual drain valve below LP separator. Lever-operated floating ball, locked closed.",
  },
  {
    caseTitle: "Fuel gas manual isolation valve",
    projectName: "Rabigh Power Block 2",
    clientName: "ARAMCO Power",
    areaUnit: "Unit 700 — Fuel Gas Skid",
    lineNumber: '4"-FG-701-A1A',
    tagNumber: "HV-7011",
    pipeSize: '4"',
    pressureClass: "300#",
    lineClass: "A1A — CS, Class 300",
    installationLocation: "Onshore - Open Air",
    valveFunction: "Isolation (On/Off)",
    serviceType: "Fuel Gas",
    fluidType: "Gas / Vapor",
    designTemp: "80",
    designPressure: "28",
    operatingPressure: "22",
    operatingTemp: "35",
    flowCondition: "Continuous",
    additionalRequirements: [
      "Hazardous Area (ATEX / IECEx)",
      "Low Emission (Fugitive Emissions)",
    ],
    notes: "Manual block valve at gas turbine fuel gas inlet. Fire-safe required.",
  },
  {
    caseTitle: "Instrument air isolation valve",
    projectName: "Jubail Utilities Expansion",
    clientName: "SABIC Utilities",
    areaUnit: "Unit 900 — IA Distribution",
    lineNumber: '1\"-IA-902-U1U',
    tagNumber: "HV-9024",
    pipeSize: '1"',
    pressureClass: "150#",
    lineClass: "U1U — Utility, Class 150",
    installationLocation: "Onshore - Sheltered / Building",
    valveFunction: "Isolation (On/Off)",
    serviceType: "Instrument Air",
    fluidType: "Gas / Vapor",
    designTemp: "60",
    designPressure: "12",
    operatingPressure: "7",
    operatingTemp: "30",
    flowCondition: "Intermittent",
    additionalRequirements: [],
    notes: "Manual block at IA header takeoff to instrument bank.",
  },
  {
    caseTitle: "Cooling water butterfly valve",
    projectName: "Ras Tanura Refinery Cooling Loop",
    clientName: "ARAMCO Refining",
    areaUnit: "Unit 800 — Cooling Tower",
    lineNumber: '24"-CW-803-W1W',
    tagNumber: "HV-8031",
    pipeSize: '24"',
    pressureClass: "150#",
    lineClass: "W1W — CS, Class 150",
    installationLocation: "Onshore - Open Air",
    valveFunction: "Isolation (On/Off)",
    serviceType: "Cooling Water",
    fluidType: "Liquid - Clean",
    designTemp: "55",
    designPressure: "10",
    operatingPressure: "5",
    operatingTemp: "38",
    flowCondition: "Continuous",
    additionalRequirements: [],
    notes: "Cooling water supply header isolation. Wafer butterfly with gear operator.",
  },
  {
    caseTitle: "Firewater ring main valve",
    projectName: "LNG Train 4 Safety Upgrade",
    clientName: "QatarEnergy LNG",
    areaUnit: "Unit 950 — Firewater",
    lineNumber: '12"-FW-951-F1F',
    tagNumber: "HV-9512",
    pipeSize: '12"',
    pressureClass: "300#",
    lineClass: "F1F — CS, Class 300, painted",
    installationLocation: "Marine / Coastal (Saline Atmosphere)",
    valveFunction: "Isolation (On/Off)",
    serviceType: "Utility Water",
    fluidType: "Liquid - Clean",
    designTemp: "50",
    designPressure: "20",
    operatingPressure: "12",
    operatingTemp: "35",
    flowCondition: "Static, ready-to-flow",
    additionalRequirements: ["Bidirectional Sealing"],
    notes: "Firewater ring main sectionalising valve. Locked open, gear operated, position indicator.",
  },
  {
    caseTitle: "HP steam isolation valve",
    projectName: "BFW & Steam Revamp",
    clientName: "Reliance Refining",
    areaUnit: "Unit 600 — HRSG",
    lineNumber: '6"-HS-602-S1S',
    tagNumber: "HV-6021",
    pipeSize: '6"',
    pressureClass: "900#",
    lineClass: "S1S — A335 P11, Class 900",
    installationLocation: "Onshore - Open Air",
    valveFunction: "Isolation (On/Off)",
    serviceType: "High Pressure Steam",
    fluidType: "Steam",
    designTemp: "440",
    designPressure: "115",
    operatingPressure: "98",
    operatingTemp: "415",
    flowCondition: "Continuous, superheated",
    additionalRequirements: ["Thermal Insulation (Jacketed)"],
    notes: "HP superheated steam main block. OS&Y gate valve, pressure-seal bonnet.",
  },
  {
    caseTitle: "Chemical injection valve",
    projectName: "Corrosion Inhibitor Skid Upgrade",
    clientName: "ADNOC Onshore",
    areaUnit: "Unit 320 — Chem Inj.",
    lineNumber: '1/2"-CI-321-C1C',
    tagNumber: "HV-3215",
    pipeSize: '1/2"',
    pressureClass: "1500#",
    lineClass: "C1C — SS 316, Class 1500",
    installationLocation: "Onshore - Open Air",
    valveFunction: "Isolation (On/Off)",
    serviceType: "Corrosive / Sour Service",
    fluidType: "Liquid - Clean",
    designTemp: "70",
    designPressure: "210",
    operatingPressure: "180",
    operatingTemp: "45",
    flowCondition: "Intermittent, low flow",
    additionalRequirements: ["Hazardous Area (ATEX / IECEx)"],
    notes: "High-pressure chemical injection block. NACE compliant trim, needle/globe.",
  },
  {
    caseTitle: "Sour gas line valve",
    projectName: "Khurais Sour Gas Gathering",
    clientName: "ARAMCO Upstream",
    areaUnit: "Unit 150 — Sour Gas Manifold",
    lineNumber: '10"-SG-152-H1H',
    tagNumber: "MOV-1525",
    pipeSize: '10"',
    pressureClass: "900#",
    lineClass: "H1H — LTCS NACE, Class 900",
    installationLocation: "Onshore - Open Air",
    valveFunction: "Isolation (On/Off)",
    serviceType: "Corrosive / Sour Service",
    fluidType: "Gas / Vapor",
    designTemp: "85",
    designPressure: "145",
    operatingPressure: "120",
    operatingTemp: "55",
    flowCondition: "Continuous, wet sour gas",
    additionalRequirements: [
      "ESD / Emergency Shutdown",
      "Low Emission (Fugitive Emissions)",
      "Hazardous Area (ATEX / IECEx)",
    ],
    notes: "Sour gas manifold ESD valve. NACE MR0175, fire-safe API 607, fugitive emission ISO 15848-1.",
  },
  {
    caseTitle: "Slurry / dirty liquid service valve",
    projectName: "Tailings Transfer Line",
    clientName: "BHP Mineral Sands",
    areaUnit: "Unit 250 — Slurry Pumping",
    lineNumber: '6"-SL-253-D1D',
    tagNumber: "HV-2531",
    pipeSize: '6"',
    pressureClass: "300#",
    lineClass: "D1D — DSS, Class 300",
    installationLocation: "Onshore - Open Air",
    valveFunction: "Isolation (On/Off)",
    serviceType: "General Hydrocarbon",
    fluidType: "Liquid - Dirty/Slurry",
    designTemp: "70",
    designPressure: "30",
    operatingPressure: "18",
    operatingTemp: "40",
    flowCondition: "Continuous, abrasive",
    additionalRequirements: ["Bidirectional Sealing"],
    notes: "Slurry transfer block. Lubricated plug or full-bore ball, hardened trim.",
  },
  {
    caseTitle: "Relief valve inlet/outlet isolation",
    projectName: "Flare Network Compliance Upgrade",
    clientName: "TotalEnergies Refining",
    areaUnit: "Unit 500 — Flare Header",
    lineNumber: '6"-FL-503-R1R',
    tagNumber: "CSO-5031",
    pipeSize: '6"',
    pressureClass: "150#",
    lineClass: "R1R — CS, Class 150",
    installationLocation: "Onshore - Open Air",
    valveFunction: "Isolation (On/Off)",
    serviceType: "Flare / Relief",
    fluidType: "Gas / Vapor",
    designTemp: "200",
    designPressure: "10",
    operatingPressure: "1",
    operatingTemp: "60",
    flowCondition: "Static, ready-to-flow on relief",
    additionalRequirements: [
      "Hazardous Area (ATEX / IECEx)",
      "Low Emission (Fugitive Emissions)",
    ],
    notes: "Car-sealed-open block valve at PSV inlet. Full bore gate, locked open, API 526 compatible.",
  },
];

export function pickRandomSample(exclude?: string): SampleCase {
  const pool = exclude ? SAMPLE_CASES.filter((c) => c.caseTitle !== exclude) : SAMPLE_CASES;
  return pool[Math.floor(Math.random() * pool.length)];
}
